### PR TITLE
add uk

### PR DESCRIPTION
**Pull request by Geniy83**
Hello. Added Ukrainian translation. How to check, please make APK for phone and watch

### CODE REVIEW

**Comment by j-kaltes** [comment]
Here are the apks:
Phone: https://drive.google.com/file/d/1P1KaZqx70GnyMdVybH33Hygt_oRYXeu1/view?usp=drive_link
Watch: https://drive.google.com/file/d/1EOJR19csaX4IsXUkeQSCNHARoGmgpoj0/view?usp=drive_link
I made two modifications in your help texts:
    • The name of the French translator pointed to your e-mail address.
    • An adb command was translated in the settings help.

**Comment by Geniy83** [comment]
Thank you

**Comment by Geniy83** [comment]
Can you change Juggluco to automatically take the language from the system language list, and not specifically just the system's main language. Users from Belarus began to write to me about this "problem". It turned out to be not very convenient for them. It is more convenient for Juggluco to take the first language that it has a translation from the entire list of system languages and accept it. Thank you for the work you've done

**Comment by j-kaltes** [comment]
The help and strings.xml of the system language is automatically used.  The order of languages in Android settings seems to be ignored. Do you know an app that takes the second mentioned language in android settings because it doesn't support the system language?

**Comment by Geniy83** [comment]
I did some testing. In the system I have loaded 2 languages Russian and Belarusian. Russian is set as the main one, and Belarusian is the second. And Juggluco turns out to be in English, that is, he did not see the second language in the system - Belarusian. Then I make Belarusian the main language of the system, and Russian the second language and Juggluco used this and was with a translation into Belarusian.
When you sent me the intermediate version 4.17.3 earlier, this problem did not exist. It has appeared since version 4.17.4

**Comment by j-kaltes** [comment]
No, this is exactly how it always works. Apps take the system language, that is determined by Android. Version 4.17.3 didn't behave differently. Only the menu was different (text from bejugglucotext.cpp), but the help and the strings out of strings.xml were in the system language. It behaved so strange, because the language wasn't turned back to the language at startup, as I described earlier.
It is possible to manually set the language, though. I don't know whether it is possible to take the second language mentioned in Android settings.

**Comment by j-kaltes** [comment]
I have put your addition in Juggluco 4.19.0. https://www.juggluco.nl/Juggluco/download.html
If you want to change something, you have to be very fast.

**Pull request merged**
