### PR TITLE
4.14.1

### PR DESCRIPTION
**Pull request by Geniy83**
Hello. Finished translation, please take a look. If you don't mind, create an APK. Your previous APK [https://drive.google.com/file/d/1TofJCPVPumw-7l_MdqPS8LbF4voNZcCI/view?usp=share_link](url) was not translated into Belarusian. Or maybe I didn't understand something (((

### CODE REVIEW

**Comment by j-kaltes** [comment]
The help of the previous APK was Belarusian, but not the interface and you needed to set the phone to Belarusian. Also the labels and shortcuts are only used with new installs.
I have made some changes to your translation to be able to build the app. The example labels have to be much shorter. You can find out yourself which size is permitted by making a new label in the app itself (left menu->Settings->Number labels).
I also use "System UI" in English, because on one phone the longer Belarusian translation wasn't displayed properly. I also think that the translation for "Last scan" is too long.
To use the labels for months, I needed to increase the size from 5 to 13 bytes. All previous languages used only 3 characters and that became 5 bytes because of one accented character somewhere and a terminating 0. Are there no three letter abbreviations for months in Belarusian?
In strings.xml I also had to change one `'` into `\'`.
I have uploaded the modified files.
https://raw.githubusercontent.com/j-kaltes/Juggluco/primary/Common/src/main/cpp/curve/bejugglucotext.cpp
https://raw.githubusercontent.com/j-kaltes/Juggluco/primary/Common/src/main/res/values-be/strings.xml
If you have a WearOS watch, I can also send you a WearOS version. The phone connected to my WearOS watch, doesn't know Belarusian and the watch gets its language from the phone, so I can't see it myself on my watch.
PHONE version: https://drive.google.com/file/d/1UklUQOc1-uY9xbg0toemPTtmeu4WDA1n/view?usp=share_link

**Comment by Geniy83** [comment]
Yes, indeed, in the phone where I tested this application, the Belarusian language was disabled.
Thank you for your help. When translating into Ukrainian, I will take into account all your comments and do everything optimally.
In Belarusian, according to ISO, there is no three-letter abbreviation for all months, but I will think about how to change this. I will be grateful to you if you send WearOS.
At Telegram, I run a large group to help people install and set up all diabetes apps and monitoring systems (FreeStyle Libre 1-3 and DEXCOM G4-G6). I provide this assistance free of charge.
Now I will translate into Ukrainian.
Thank you very much for your feedback and the great Juggluco app!

**Comment by j-kaltes** [comment]
On the WearOS emulator Dark mode seems to be too large:
leftmenu
Is "(save)" needed?
save

WearOS version: https://drive.google.com/file/d/1MPvBqYpcEdg8G-e-PwFtPcdzZ5wFD5Q_/view?usp=share_link

I can now also change the phone's locale with: https://play.google.com/store/apps/details?id=jp.co.c_lis.ccl.morelocale

**Comment by Geniy83** [comment]
I will reset the Juggluco-be application by the user and collect all comments from them and make a change

**Comment by j-kaltes** [comment]
I changed battery.html and settinghelp.html because an adb command was translated.
The file after the change.
Phone:   https://drive.google.com/file/d/1FOlxykttuHsG17h3EVwTn6eqw3fpA1xe/view?usp=share_link
I added a modified staticnum.html to the wearos version, I hope it is Belarusian: https://drive.google.com/file/d/1YPYOK6vFv1rS279CdKNzlwwB2rfxnv0d/view?usp=share_link
I found something that doesn't fit totally on a small WearOS display:
uploader

**Comment by j-kaltes** [comment]
I already solved the difficulty in the uploader by exchanging the position of two items:
uploader
Here are the new files:
Watch: https://drive.google.com/file/d/1p0O7RsnjeJn7YLnw0_RLdJb1lhJWdJM7/view?usp=share_link

EDIT:
PHONE: https://drive.google.com/file/d/1IcP74Jqi0NhY1DPTRhuNPmroLTQ2rS7L/view?usp=share_link

**Comment by Geniy83** [comment]
Thank you so much!!! You are the best))

**Comment by j-kaltes** [comment]
The Belarusian translation of _Dark mode_ doesn't fit very well on the WearOS screen:
darkmode
The following fits better on the screen. I don't know whether you can leave "Dark mode' untranslated. According the the Italian translator it could in Italy. What about translating "Mirror" in the Belarusian translation of _Clone_? I have done so in the Dutch and German translation and it is also done in the Polish. One can't use the Dutch translation of "Mirror"  to refer to a website that has the same content as another website.
NewLeft
rightbe

The previous phone apk probably didn't work in the Belarusian translation:
Phone: https://drive.google.com/file/d/1HnHoDtEg9XWOS2jl-g1bR1iS7EQN0vr-/view?usp=share_link
Watch: https://drive.google.com/file/d/1syqeUpSfyxAxyy_zekPiBGNgP3LRmcV5/view?usp=share_link (new)

**Comment by Geniy83** [comment]
Yes, let's leave the _Dark Mode_ without translation and the Сlone ("**Клон**") is correctly translated and the word is shorter. Just need to fix it then Jugglucohelp, I'll do it.
I have a small question. To transfer data from Juggluco to xDrip, do you need to check the _Patched Libre broadcast_ (this is the previous _Send to xDrip_)?

**Comment by j-kaltes** [comment]
OK. I probably can also better put "_Dark mode_" in the phone version.
Yes the "_Patched Libre broadcast_" can be used to send glucose values to xDrip and this was previously called "_Send to xDrip_", but now it can also be used for xDrips with a different Application ID and other apps.

**Comment by j-kaltes** [comment]
I have uploaded the modified files to the github. So that you can modify them:
https://raw.githubusercontent.com/j-kaltes/Juggluco/primary/Common/src/main/res/values-be/strings.xml
https://raw.githubusercontent.com/j-kaltes/Juggluco/primary/Common/src/main/cpp/curve/bejugglucotext.cpp

The original also contains some changes:
https://raw.githubusercontent.com/j-kaltes/Juggluco/primary/Common/src/main/res/values/strings.xml
And I added a help file:
https://raw.githubusercontent.com/j-kaltes/Jugglucohelp/primary/talkhelp.html

**Pull request closed without merging**
